# Generated by Django 3.1.4 on 2020-12-15 20:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_data',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 15, 20, 40, 0, 231796, tzinfo=utc), verbose_name='publish date'),
        ),
    ]
